language: rust

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8  # needed for local Neo4j

env:
  # test across multiple versions of Neo4j:
  - NEO4J_VERSION="3.1.1"
  - NEO4J_VERSION="2.3.8"

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

matrix:
  allow_failures:
    - rust: nightly
