[package]
name = "rusted_cypher"
version = "0.9.1"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "Send cypher queries to a neo4j database"
repository = "https://github.com/livioribeiro/rusted-cypher"
homepage = "https://github.com/livioribeiro/rusted-cypher"
documentation = "http://livioribeiro.github.io/rusted_cypher/rusted_cypher/"
readme = "README.md"
keywords = ["neo4j", "database", "query", "cypher", "graph"]
license = "MIT OR Apache-2.0"
build = "build.rs"
include = [
  "src/**/*",
  "build.rs",
  "Cargo.toml",
  "LICENSE-*",
  "README.md",
  "CHANGELOG.md",
]

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.7", optional = true }
syntex = "0.31"

[dependencies]
hyper = "0.8"
url = "0.5"
serde = "0.7"
serde_json = "0.7"
serde_macros = { version = "0.7", optional = true }
rustc-serialize = { version = "0.3", optional = true }
semver = "0.2"
time = "0.1"
quick-error = "1.0"
log = "0.3"
