[package]
name = "rusted_cypher"
version = "0.1.0"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "Send cypher queries to a neo4j database"
repository = "https://github.com/livioribeiro/rusted-cypher"
homepage = "https://github.com/livioribeiro/rusted-cypher"
readme = "README.md"
keywords = ["neo4j", "database", "query", "cypher", "graph"]
license = "MIT"

[dependencies]
hyper = "0.6"
url = "0.2"
serde = "0.5"
serde_json = "0.5"
serde_macros = "0.5"
semver = "0.1"
