[package]
name = "rusted_cypher"
version = "0.9.1"
authors = ["Livio Ribeiro <livioribeiro@outlook.com>"]
description = "Send cypher queries to a neo4j database"
repository = "https://github.com/livioribeiro/rusted-cypher"
homepage = "https://github.com/livioribeiro/rusted-cypher"
documentation = "http://livioribeiro.github.io/rusted_cypher/rusted_cypher/"
readme = "README.md"
keywords = ["neo4j", "database", "query", "cypher", "graph"]
license = "MIT OR Apache-2.0"
build = "build.rs"
include = [
  "src/**/*",
  "build.rs",
  "Cargo.toml",
  "LICENSE-*",
  "README.md",
  "CHANGELOG.md",
]

[dependencies]
hyper = "0.10"
url = "1.3"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
semver = "0.5"
time = "0.1"
quick-error = "1.1"
log = "0.3"
